### ISSUE TITLE
Use parallel threads to check Hosts status

### ISSUE THREAD

**Issue by LamaKing** [lcm-unimi/labcalcoloctl#1]
The ssh calls to the nodes are made in serial. This way the process is really slow (up to 13s to query the 13 nodes of LCM1).
It would be nice to do something similare to what is done in the whoall script, which is way faster.
I'd like to do it, but I'm not sure I know how to.

**Comment by napalm5** [comment]
The issue was solved with the latest merge from Silva's branch
